### ISSUE TITLE
Video link doesn't appear anywhere in published proposal

### ISSUE THREAD

**Issue by chillsauce** [atticlab/eos-wps-front#21]
The video URL I provided in the "setup" step of the proposal doesn't appear anywhere on the proposal for those viewing it.

**Comment by StanCheb** [comment]
The corresponding card now appears in the "Oveview" tab if a video link is provided:

![Screenshot (3)](https://user-images.githubusercontent.com/42133844/72505508-bf822680-3848-11ea-83d2-4e19c3d36817.png)
