### ISSUE TITLE
Don't automatically prompt a user to sign in on landing 

### ISSUE THREAD

**Issue by chillsauce** [atticlab/eos-wps-front#23]
Currently users are prompted to sign in as soon as they land on the website. They're not able to browse the proposals until they sign in or dismiss the prompt in Scatter.

Users should only be prompted to sign in when clicking the sign in button or attempt to take some action that requires they are signed in. 

Users should be able to browse proposals without being interrupted.

**Comment by miclekoby** [comment]
We've removed initial scatter pop up. User will be automatically logged in if he previously used scatter on the site
