### ISSUE TITLE
FAQ changes

### ISSUE THREAD

**Issue by chillsauce** [atticlab/eos-wps-front#47]
Please add the following question/answer to the FAQ section, after the "Who can participate in voting on EOS WPS proposals?" question:

Q: How much work can be expected to get a proposal funded?
A: Data from other WPS shows that a lot of work is required to get a proposal funded. It is up to the proposer to seek and obtain votes on the proposal. The network does not provide guidance, nor guarantee, as to how to get funded. 

Please update the answer for the "Is the 100 EOS fee ever refunded?" question as follows:

No, the fee is non-refundable once the proposal has been published. However, during the draft period of a proposal, the deposit of 100 EOS can be refunded.

**Comment by StanCheb** [comment]
Ready
