### ISSUE TITLE
content tweak for "about" section

### ISSUE THREAD

**Issue by chillsauce** [atticlab/eos-wps-front#48]
Please update the "Voting periods and funding" section as follows:

A maximum budget of 50,000 EOS will be made available for each 30-day voting period. The period budget and duration are settings within the WPS smart contract that can be adjusted by MSIG approval from 15 of the top 21 Block Producers. 

eosio.wps is funded from the fees accumulated in the eosio.names and eosio.ramfee accounts prior to the deployment of REX. Prior to REX, these accounts accumulated roughly 3.5 million EOS from EOS premium name auctions and RAM purchase fees. An MSIG approval from 15 of the top 21 Block Producers is required to move those funds to eosio.wps. 

Any on-going fees being collected by `eosio.names` & `eosio.ramfee` will continue to flow to REX holders and shall not be transferred to `eosio.wps`. Funds flowing into REX will not be affected by this proposal.

We’ll propose to transfer 50,000 EOS, or two periods worth, to the eosio.wps account upon activation of the EOS WPS system. We’ll propose a top-up of another 25,000 EOS one month ahead of each period. This gives the top 21 the flexibility to discontinue the WPS system at any time by simply not funding it.

**Comment by StanCheb** [comment]
Done
