### ISSUE TITLE
Reduce vertical space in list view

### ISSUE THREAD

**Issue by chillsauce** [atticlab/eos-wps-front#52]
The list view of Active Proposals should enable you to see many proposals at the same time without scrolling. The cards for proposals in list view are currently tall, containing a lot of vertical blank space, limiting the number of proposals that can be viewed at once. 

![Screen Shot 2020-03-12 at 3 55 20 PM](https://user-images.githubusercontent.com/37008057/76649957-03876400-6538-11ea-8219-2cd618f43d5e.png)

Reduce the vertical space used by proposals in list view, and the space between them, similar to how they appear in DASH Nexus. 
nice-to-have: allow the cards to be expanded to display additional info and a graph of votes over time.

See example:
![photo_2020-03-13_14-37-50](https://user-images.githubusercontent.com/37008057/76650286-a17b2e80-6538-11ea-8d9b-fe85efc6dd0a.jpg)

**Comment by StanCheb** [comment]
The layout of lists is changed to tables. That way a user is able to see quite a lot of proposals at once.
