### ISSUE TITLE
Add `comment` feature

### ISSUE THREAD

**Issue by DenisCarriere** [atticlab/eos-wps-front#65]
## Feature `comment`

If we could add a `discussion/comments` section to the UI with the following features:

- [ ] create/modify/delete comment
- [ ] only eligible accounts can comment:
  - proposer
  - voters (eligible BPs)
- [ ] show all comments per single proposal ordered by date
  - table => `comments`
  - scope => `proposal_name`
  - multi-index (by timestamp) => `index_position = 2`
- [ ] `comment_json` schema can be very simple initially:
  - { "key": "text", "value": "my comment" }

> Note: Accounts can only comment once per proposal, however, they can edit/delete their comment during the proposal's `active` status.

## ACTION `comment`

- **authority**: `account`
- **ram_payer**: `account`

### params

- `{name} account` - account name
- `{name} proposal_name` - proposal name
- `{map<name, string>} metadata_json` - a sorted container of <key, value>

### example

```bash
# create/modify comment
cleos push action eosio.wps comment '["myaccount", "myproposal", [{ "key": "text", "value": "my comment" }]]' -p myaccount

# delete comment
cleos push action eosio.wps comment '["myaccount", "myproposal", []]' -p myaccount
```

## TABLE `comments`

- scope: `proposal_name`
- ram_payer: `account`

### multi-indexes

| `param`     | `index_position` | `key_type` |
|-------------|------------------|------------|
| `timestamp` | 2                | i64        |

### params

- `{name} account` - account name
- `{time_point_sec} timestamp` - last time created/modified
- `{uint16_t} version` - version number
- `{map<name, string>} metadata_json` - a sorted container of <key, value>

### example

```json
{
  "account": "myaccount",
  "timestamp": "2020-03-26T12:00:00",
  "version": 0,
  "metadata_json": [
    { "key": "text", "value": "my comment" }
  ]
}
```

**Comment by StanCheb** [comment]
Done.
