### ISSUE TITLE
add discussion channels as metadata (Slack/Telegram/WeChat)

### ISSUE THREAD

**Issue by DenisCarriere** [atticlab/eos-wps-front#66]
To help further discussion, would be ideal to have the `proposer` be able to include in the `draft::metadata_json`:
- Slack
- Telegram
- WeChat

That way those discussion channels are "authoritative" groups created by the proposer.

**Comment by StanCheb** [comment]
Done. There is now a possibility to add a discussion chanel on the first step of proposal creation.
