### ISSUE TITLE
Add `proposers` feature

### ISSUE THREAD

**Issue by DenisCarriere** [atticlab/eos-wps-front#67]
Allows the `proposer` to post metadata about themselves:

### `metadata_json` (example)
- name
- description
- website
- telegram
- wechat

### params

- `{name} proposer` - proposer of proposal
- `{map<name, string>} metadata_json` - a sorted container of <key, value>

### example

```json
{
  "proposer": "myaccount",
  "metadata_json": [
    { "key": "region", "value": "global" }
  ]
}
```

## ACTION `setproposer`

Set proposer's metadata

- **authority**: `proposer`
- **ram_payer**: `proposer`

### params

- `{name} proposer` - proposer of proposal
- `{map<name, string>} metadata_json` - a sorted container of <key, value>

### example

```bash
cleos push action eosio.wps setproposer '["myaccount", [{"key":"region", value":"global"}]]' -p myaccount
```

**Comment by StanCheb** [comment]
Done.
