### ISSUE TITLE
Check eligible proposer (disable submitdraft & activate)

### ISSUE THREAD

**Issue by DenisCarriere** [atticlab/eos-wps-front#68]
Check eligible proposer (disable submitdraft & activate)

This check prevents `proposer` to also be `voter`

https://github.com/EOS-Nation/eos-wps/commit/9552d86b947467bf8b596f88f01cba6b4777e40b

**Comment by miclekoby** [comment]
fixed
https://github.com/atticlab/eos-wps-front/pull/72
